steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '.'
      - '-t'
      - '$_PROJECT_REGION-docker.pkg.dev/$PROJECT_ID/webperfly:$COMMIT_SHA'
      - '--build-arg=NEXTAUTH_URL=$_NEXTAUTH_URL'
      - '--build-arg=NEXT_PUBLIC_BASE_URL=$_NEXT_PUBLIC_BASE_URL'
      - '--build-arg=NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=$_NEXT_PUBLIC_GOOGLE_ANALYTICS_ID'
      - '--build-arg=FIREBASE_API_KEY=$_FIREBASE_API_KEY'
      - '--build-arg=FIREBASE_AUTH_DOMAIN=$_FIREBASE_AUTH_DOMAIN'
      - '--build-arg=FIREBASE_DATABASE_URL=$_FIREBASE_DATABASE_URL'
      - '--build-arg=FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID'
      - '--build-arg=FIREBASE_STORAGE_BUCKET=$_FIREBASE_STORAGE_BUCKET'
      - '--build-arg=FIREBASE_MESSAGING_SENDER_ID=$_FIREBASE_MESSAGING_SENDER_ID'
      - '--build-arg=FIREBASE_APP_ID=$_FIREBASE_APP_ID'
      - '--build-arg=FIREBASE_MEASUREMENT_ID=$_FIREBASE_MEASUREMENT_ID'
      - '--build-arg=GOOGLE_CLIENT_ID=$_GOOGLE_CLIENT_ID'
      - '--build-arg=GOOGLE_CLIENT_SECRET=$_GOOGLE_CLIENT_SECRET'
      - '--build-arg=SECRET=$_SECRET'

  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_PROJECT_REGION-docker.pkg.dev/$PROJECT_ID/webperfly:$COMMIT_SHA'
  
  # Deploy to cloud run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'beta'
      - 'deploy'
      - '--image=$_PROJECT_REGION-docker.pkg.dev/$PROJECT_ID/webperfly:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - 'webperfly'

# replacements variables
substitutions:
  _PROJECT_REGION: 'us-central1'

images:
  - '$_PROJECT_REGION-docker.pkg.dev/$PROJECT_ID/webperfly:$COMMIT_SHA'

timeout: 1200s
