steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_PROJECT_REGION-docker.pkg.dev/$PROJECT_ID/webperfly:$COMMIT_SHA'
      - '--build-arg=NEXTAUTH_URL=$NEXTAUTH_URL'
      - '--build-arg=NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL'
      - '--build-arg=FIREBASE_API_KEY=$FIREBASE_API_KEY'
      - '--build-arg=FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN'
      - '--build-arg=FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL'
      - '--build-arg=FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID'
      - '--build-arg=FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET'
      - '--build-arg=FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID'
      - '--build-arg=FIREBASE_APP_ID=$FIREBASE_APP_ID'
      - '--build-arg=FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID'
      - '--build-arg=GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID'
      - '--build-arg=GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET'
      - '--build-arg=SECRET=$SECRET'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_PROJECT_REGION-docker.pkg.dev/$PROJECT_ID/webperfly:$COMMIT_SHA'
  
  # Deploy to cloud run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'beta'
      - 'deploy'
      - '--image=$_PROJECT_REGION-docker.pkg.dev/$PROJECT_ID/webperfly:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - 'webperfly'

images:
  - '$_PROJECT_REGION-docker.pkg.dev/$PROJECT_ID/webperfly:$COMMIT_SHA'

timeout: 1200s
